site_name: MetalCore Server
site_url: https://metalcore.silaseacret.com/
theme:
   name: terminal
   palette: gruvbox_dark
   features:
      - footer.prev_next
      #- navigation.side.hide
      - navigation.side.indexes
      #- navigation.side.toc.hide
      #- navigation.top.hide
      #- navigation.top.cursor_animation.hide
      #- navigation.top.search_button.hide
      - revision.date
      - revision.history
      - style.links.underline.hide